name: CI with SonarQube

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout Code
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -----------------------------
      # Start SonarQube in Docker
      # -----------------------------
      - name: Start SonarQube Server
        run: |
          docker run -d --name sonarqube \
            -p 9000:9000 \
            sonarqube:lts-community

          echo "Waiting for SonarQube to be fully up..."
          sleep 90  # SonarQube needs time to boot

      # -----------------------------
      # Install Node
      # -----------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # -----------------------------
      # Install Dependencies
      # -----------------------------
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # -----------------------------
      # Run Angular Tests (Coverage)
      # -----------------------------
      - name: Run Tests with Coverage
        run: npm run test -- --watch=false --code-coverage

      # -----------------------------
      # Run SonarQube Scanner
      # -----------------------------
      - name: Run SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@master
        with:
          host-url: "http://localhost:9000"
          token: ${{ secrets.SONAR_TOKEN }}

      # -----------------------------
      # Stop SonarQube
      # -----------------------------
      - name: Stop SonarQube
        run: docker stop sonarqube
